### ISSUE TITLE
Revocation check should be implemented

### ISSUE THREAD

**Issue by mlegner** [admin-ch/CovidCertificate-SDK-Android#2]
https://github.com/admin-ch/CovidCertificate-App-Android/blob/060a40c7510c113a304ebe515e0f7833ae03623b/eval/src/main/java/ch/admin/bag/covidcertificate/eval/Eval.kt#L84-L86

I suspect that the revocation check should do more than just return `SUCCESS`.

**Comment by goebelUB** [comment]
The revocation check is now implemented on main and will be in the next release.
