### ISSUE TITLE
Can't decode data at API level lower than 26.

### ISSUE THREAD

**Issue by Lucien-Hsu** [admin-ch/CovidCertificate-SDK-Android#62]
I use this SDK on device at API level  27 well, but When I run it on device at **API level  25**, it can't decode.

`val expirationTime: Instant? = map[CwtHeaderKeys.EXPIRATION.asCBOR()]?.let { Instant.ofEpochSecond(it.AsInt64()) }`
 in CborService.kt will throw an exception message like that:
`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;`

I looked it up on the internet, and found that java.time package was added only in **API 26.**

Is this a bug or i'm missing something?

**Comment by goebelUB** [comment]
[Desugaring](https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/main/sdk/build.gradle#L39) should take care of that 🤔 
Does it work if you [enable desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) in your app (so it isn't just in the SDK)?

**Comment by Lucien-Hsu** [comment]
I don't know about that. 
Thank you, this really help me.

**Comment by goebelUB** [comment]
Great!
It's curious though, I would have thought that specifying it in the SDK is sufficient. Learning something every day :)
