### ISSUE TITLE
Test certificate for the ABN or DEV environment

### ISSUE THREAD

**Issue by luzianscherrer** [admin-ch/CovidCertificate-SDK-Android#65]
Are there any test certificates available that could be used in the SdkEnvironment.ABN or SdkEnvironment.DEV environment?

**Comment by goebelUB** [comment]
The certs in the [EU testdata repo](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CH) should work on ABN.

**Comment by luzianscherrer** [comment]
Perfect, thanks!
