### ISSUE TITLE
Support for android sdk 24

### ISSUE THREAD

**Issue by pxanzer3553** [admin-ch/CovidCertificate-SDK-Android#66]
Hello, i got an issue when integrate this SDK to my app (cordova app). The app crash for people who use android 7.0. The issue come from java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant.
https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/03a42973c2713ab21a66e8a7ef6afba2208ed726/sdk/src/main/java/ch/admin/bag/covidcertificate/sdk/android/repository/TrustListRepository.kt#L24. that only avaiable on sdk version 26.
This issue is very critical for me. Do i need to add something to fix this? I saw the mínSdk is 23 for the sdk here
Thank for any help.

**Comment by goebelUB** [comment]
See also #62. As a workaround try [enabling desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) in your app.
I still need to find out why it's not sufficient to have desugaring just in the SDK, even when `java.time.Instant` et al are only used in the SDK.

**Comment by pxanzer3553** [comment]
After add desugaring to gradle file. The crash is gone, thank for your suggestion. @goebelUB
