### ISSUE TITLE
StateError(code=G|NWF, message=null, certificateHolder=null) in release version

### ISSUE THREAD

**Issue by Jacksotnik** [admin-ch/CovidCertificate-SDK-Android#73]
Hello. In debug mode verification works fine.
But in production we receive verification error "StateError(code=G|NWF, message=null, certificateHolder=null)"

What can be reason?

**Comment by vietnt134** [comment]
I have the same issue, can you tell me how to fix it :)
Many thanks

**Comment by Jacksotnik** [comment]
Hello. 
In my case i have set "minifyEnabled false"

**Comment by vietnt134** [comment]
wow, thank for a very quick reply...I can run it now :D
