### ISSUE TITLE
1.5.5 sdk size

### ISSUE THREAD

**Issue by Jacksotnik** [admin-ch/CovidCertificate-SDK-Android#91]
Hi there. Comparing with previous sdk version(1.5.4), size increased for more than 10Mb. Is it normal?

**Comment by goebelUB** [comment]
Yes, that's expected. While migrating the list of revoked UVCIs from file storage to a database, we decided to also include the current list in the SDK. Thus clients only need to get the diff from the backend, rather than the entire list.

**Comment by Jacksotnik** [comment]
Clear. Thank you for quick answer :)
